name: Automation of tests on push and merge

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "release" branch
  push:
    branches: [ "main", "release", "develop" ]
  pull_request:
    branches: [ "main", "release", "develop" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Choose node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx vitest run --passWithNoTests --coverage
        #To be changed, if tests will not be included in package.json

      - name: If tests fail, send email to the tester
        if: failure()
        uses: dawidd6/action-send-mail@v8
        with:
          server_address: smtp.poczta.onet.pl
          server_port: 465
          secure: true
          username: ${{vars.EMAIL}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: 'Build Failed: ${{ github.repository }}'
          body: |
            Job ${{ github.job }} in workflow ${{ github.workflow }} has failed.
            Repository: ${{ github.repository }}
            Triggered by: ${{ github.actor }}
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: 246311@edu.p.lodz.pl
          from: ej-aj-masters@op.pl

      - name: Run build
        run: npm run build

        env:
          CI: true
      
